config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :flights
  resources :airplanes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  has_many :flights
  has_many :reservations, :through => :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:plane_model, :rows, :columns)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_with(model: airplane, local: true) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plane_model %>
    <%= form.text_area :plane_model %>
  </div>

  <div class="field">
    <%= form.label :rows %>
    <%= form.number_field :rows %>
  </div>

  <div class="field">
    <%= form.label :columns %>
    <%= form.number_field :columns %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Plane model</th>
      <th>Rows</th>
      <th>Columns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.plane_model %></td>
        <td><%= airplane.rows %></td>
        <td><%= airplane.columns %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plane model:</strong>
  <%= @airplane.plane_model %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @airplane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @airplane.columns %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>